### PR TITLE
Use XDG_CONFIG_HOME for fish and wahoo

### PR DESCRIPTION
**Pull request by jrobeson**
Let's use the XDG_CONFIG_HOME directory if it exists, in case it isn't
~/.config

### CODE REVIEW

**Comment by bucaran** [comment]
Cool. Where is this `XDG_CONFIG_HOME` directory usually located? I thought `fish` itself stored (that's how it is in my system) its configuration in `~/.config`

**Comment by jrobeson** [comment]
it's usually located at ~/.config, thus i set it to ~/.config.

**Comment by jrobeson** [comment]
like this `test -z ${XDG_CONFIG_HOME+_} && XDG_CONFIG_HOME="${HOME}/.config" `

**Comment by bucaran** [comment]
I see. Could it be somewhere else?

**Comment by jrobeson** [comment]
yep, users can set it to whatever they like as per http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

I plan on doing XDG_DATA_HOME next

**Comment by bucaran** [comment]
:+1:

**Pull request merged**
