### PR TITLE
Use XDG_DATA_HOME to store Wahoo packages

### PR DESCRIPTION
**Pull request by jrobeson**

### CODE REVIEW

**Comment by jrobeson** [comment]
i punted on renaming the variables... let's decide on this stuff first.

**Comment by bucaran** [comment]
I am not following.

**Comment by jrobeson** [comment]
I mentioned that i wanted to rename the variables here: https://github.com/wa/wahoo/issues/87

**Comment by bucaran** [comment]
Right.

> i punted on renaming the variables... let's decide on this stuff first.

What do you want to decide? Is this PR ready to merge?

**Comment by jrobeson** [comment]
this PR is ready to merge.. if you approve it. then i will submit another PR to change the name of BASE and CUSTOM and add a WAHOO_ prefix

**Comment by jrobeson** [comment]
please examine it carefully

**Comment by bucaran** [comment]
I see. Any chance you can close this one and put everything in one PR? :smile:

**Comment by jrobeson** [comment]
hah.. i actually did it as one PR first and then split it to keep two potentially contentious issues separate :)

**Comment by bucaran** [comment]
It's cool, this is not a major change and it would make my life easier in order to review the contents. Sorry for the trouble!

**Comment by jrobeson** [comment]
done, added in another commit.

**Comment by bucaran** [comment]
Sweet!

**Comment by bucaran** [comment]
Maybe. How does your `$WAHOO_PATH` look like? 

I find `~/.wahoo` the most convenient.

**Comment by jrobeson** [comment]
why did you merge it before asking that? It's set to `$XDG_DATA_HOME/wahoo`  which is `~/.local/share/wahoo" by default.  I personally am tired of my `$HOME` being cluttered with random dot files and makes backups more difficult to configure since you have to choose everything manually.

**Comment by jrobeson** [comment]
you should definitely read the XDG base directory specification to see why things are setup the way they are.

**Comment by bucaran** [comment]
No prob with Wahoo going in there really.

Why `$XDG_CONFIG_HOME/wahoo/installed_pkgs`?

**Comment by jrobeson** [comment]
how can you do it now? looking in ~/.config/wahoo/  I see no list of the packages that are currently installed. If i were to rm -rf $WAHOO_PATH/pkg then wahoo would have no idea what I previously had installed.

**Comment by bucaran** [comment]
So, you want to install packages in a different directory?

**Comment by jrobeson** [comment]
no. i want to keep a list of installed packages in a different directory

**Comment by bucaran** [comment]
We are not keeping a list with this information anywhere. Basically we are using WAHOO_PATH/pkg and WAHOO_CUSTOM_PATH/pkg for that.

**Comment by bucaran** [comment]
Let's create a new issue with this.

**Pull request merged**
