### PR TITLE
Move configurable env vars to top of file

### PR DESCRIPTION
**Pull request by jrobeson**
I think it makes it a bit nicer to be able to see all the configurable environment variables at the top of the file in a self documenting way.  This makes it more likely that the documentation (and defaults) for the environment variables won't get out of sync with their values.

### CODE REVIEW

**Comment by jrobeson** [comment]
I think CI should have a default value too, however I don't see CI actually being used in the codebase (including the .travis.yml), so i decided to punt on that.

**Comment by bucaran** [comment]
This is a good change! Thanks!

**Comment by jrobeson** [comment]
@bucaran : but where is/was it used?

**Comment by jrobeson** [comment]
it looked like it was supposed to be a boolean variable only? maybe i'm confused about it

**Comment by bucaran** [comment]
Here

```sh
  if lib_wahoo_install; then
    util_log_default_success "Wahoo"
    util_display_success_msg

    cd $HOME

    if [ -z ${CI+_} ]; then
      util_env_swap_process "fish"
    fi
  else
    util_log ERROR "Alas, Wahoo failed to install correctly"
    util_log INFO "Please complain here → git.io/wahoo-issues"
    exit 1
  fi
```

So, basically we don't want to swap shells if we are running in Travis, otherwise stuff will hang forever.

**Comment by jrobeson** [comment]
yes, i know where it is used in bootstrap.sh, but where else ?

**Comment by bucaran** [comment]
Optionally at the command line when the script is `curl`ed.

**Comment by jrobeson** [comment]
but shouldn't it actually be set in the travis config somewhere.. so its' actually used? https://github.com/wa/wahoo/blob/master/.travis.yml

**Comment by bucaran** [comment]
Right. You are completely right. I don't know what's going on. I swear I knew what I was doing :laughing: 

I remember having exactly the same problem when I added CI to `oh-my-fish` back in the day and was able to fix travis by doing something like this.

**Comment by bucaran** [comment]
For example, I added this bit to omf

```sh
# Launch fish after installation, loading Oh My Fish for the first time.
# Safeguard for non-interactive terminals, automated installers, etc.
if status --is-interactive
  exec fish < /dev/tty
end
```

**Comment by jrobeson** [comment]
yeah i know why CI exists, I just don't see it being used anywhere

**Comment by bucaran** [comment]
Me neither. So we should remove this as it does not make sense. I must have thought I would use it, but never did. And no problems happened so never had the need to and somehow forgot to remove it.

**Pull request merged**
