### PR TITLE
bootstrap: fix typo in util_log

### PR DESCRIPTION
**Pull request by jrobeson**

### CODE REVIEW

**Comment by bucaran** [comment]
:+1: Good catch.

**Comment by jrobeson** [comment]
I'm confused about why it says this branch has conflicts.

**Comment by jrobeson** [comment]
ah.. there we go.

**Comment by jrobeson** [comment]
can you merge it then? (once travis passes)

**Comment by bucaran** [comment]
I think travis is failing because of the CI thing. I know, it's the twilight zone.

**Comment by jrobeson** [comment]
yep.. it's a default ENV variable! http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables  go ahead and just revert that commit!

**Comment by bucaran** [comment]
It's alright, let's keep in the history so that we don't screw up again. I'm not near my computer ATM so if you can send small patch that'd be great!

**Comment by jrobeson** [comment]
ping?

**Comment by bucaran** [comment]
:+1:

**Pull request merged**
